---
title: "OilSpillsCanada"
author: "Caitlin Furby"
date: "June 28, 2017"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r eruptions, echo=FALSE, message=FALSE, warning=FALSE}
library(readr)
library(ggplot2)
library(stringr)
library(car)
library(ggmap)
library(sp)
library(leaflet)
library(geojsonio)
library(sp)
library(rgdal)
library(maps)
library(RColorBrewer)


library(readr)
OilIncident <- read_csv("~/OilGasCanada/ncdntcmprhnsv-eng.csv")
attach(OilIncident)

OilIncident$`Release Type` <- as.character(OilIncident$`Release Type`)
OilIncident$`Release Type`[OilIncident$`Release Type` == "Not Applicable"] <- NA
OilIncident <- OilIncident[!is.na(OilIncident$`Release Type`),]
OilIncident$Substance <- as.character(OilIncident$Substance)
OilIncident$Substance[OilIncident$Substance == "Not Applicable"] <- NA
OilIncident <- OilIncident[!is.na(OilIncident$Substance),]


state_popup <- paste0("<strong>Year: </strong>", 
                        OilIncident$Year,
                      "<br><strong>Date/Time Discovered: </strong>",
                        OilIncident$`Discovered Date and Time`,
                      "<br><strong>Emergency Level: </strong>",
                        OilIncident$`Emergency Level`,
                      "<br><strong>Location: </strong>",
                        OilIncident$`Nearest Populated Centre`,
                      "<br><strong>Substance: </strong>", 
                        OilIncident$Substance,
                      "<br><strong>Company: </strong>",
                        OilIncident$Company,
                      "<br><strong>Immediate Cause: </strong>",
                        OilIncident$`Immediate cause category`,
                      "<br><strong>Date Closed: </strong>",
                        OilIncident$`Closed Date`
                      )


leaflet(OilIncident) %>% addTiles() %>% addMarkers(
clusterOptions = markerClusterOptions(), popup = state_popup)

```


